/**
 * Emit TypeScript type declarations for a content schema.
 *
 * Given a `Schema`, produces a `.d.ts`-style string with:
 *
 *   - One interface per document type: `export interface Post { ... }`
 *   - A discriminated union of all document types: `export type AnyDocument = Post | Author | ...`
 *   - A helper map: `export type DocumentByType = { post: Post; author: Author; ... }`
 *
 * Reference fields expand to `{ _type: "reference"; _ref: string }` by
 * default. When the referenced type is unambiguous we also emit a
 * "dereferenced" alias: `AuthorRef = { _type: "reference"; _ref: Author["_id"] }`
 * so that projections using `author->` can narrow to the target type.
 */

import type { FieldDef, Schema } from "@repo/core/schema"

export interface EmitOptions {
  /** Module path to import types from (for the query types file). Defaults to "./schema-types". */
  schemaImport?: string
  /** Add a header comment with a timestamp + warning. Defaults to true. */
  includeHeader?: boolean
}

export function emitSchemaTypes(schema: Schema, options: EmitOptions = {}): string {
  const includeHeader = options.includeHeader !== false
  const lines: string[] = []
  if (includeHeader) {
    lines.push("// Generated by @repo/typegen. Do not edit by hand.")
    lines.push("// Re-run `bun run typegen` after schema changes.")
    lines.push("")
  }

  lines.push(`/** Common base fields present on every document. */`)
  lines.push(
    `export interface SanityCloneDocument<T extends string = string> {\n` +
      `  _id: string\n` +
      `  _type: T\n` +
      `  _rev: string\n` +
      `  _createdAt: string\n` +
      `  _updatedAt: string\n` +
      `}`,
  )
  lines.push("")

  lines.push(`/** Portable Text block (rich text content). */`)
  lines.push(
    `export interface PortableTextSpan {\n` +
      `  _type: "span"\n` +
      `  _key: string\n` +
      `  text: string\n` +
      `  marks?: string[]\n` +
      `}\n` +
      `export interface PortableTextBlock {\n` +
      `  _type: "block"\n` +
      `  _key: string\n` +
      `  style: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote"\n` +
      `  children: PortableTextSpan[]\n` +
      `  markDefs?: { _key: string; _type: string; [key: string]: unknown }[]\n` +
      `}`,
  )
  lines.push("")

  for (const type of schema.types) {
    lines.push(`/** ${type.title} */`)
    lines.push(
      `export interface ${pascal(type.name)} extends SanityCloneDocument<"${type.name}"> {`,
    )
    for (const field of type.fields) {
      if (field.hidden) continue
      lines.push(`  ${field.name}${isOptional(field) ? "?" : ""}: ${fieldType(field, schema)}`)
    }
    lines.push(`}`)
    lines.push("")
  }

  const names = schema.types.map((t) => pascal(t.name))
  lines.push(`/** Any document in this schema. */`)
  lines.push(`export type AnyDocument = ${names.join(" | ")}`)
  lines.push("")
  lines.push(`/** Map from document type name to its interface. */`)
  lines.push(`export type DocumentByType = {`)
  for (const t of schema.types) {
    lines.push(`  ${t.name}: ${pascal(t.name)}`)
  }
  lines.push(`}`)
  lines.push("")

  // Inline object types used in arrays — collected as type aliases so
  // consumers can import them individually (e.g. for slice components).
  const inlineTypes = collectInlineObjectTypes(schema)
  if (inlineTypes.size > 0) {
    lines.push(`// --- Inline object types (for use in array.of) ---`)
    lines.push("")
    for (const [typeName, field] of inlineTypes) {
      const inner = field.fields
        .map((f) => `  ${f.name}?: ${fieldType(f, schema)}`)
        .join("\n")
      lines.push(`export interface ${pascal(typeName)} {`)
      lines.push(`  _type: "${typeName}"`)
      lines.push(`  _key: string`)
      lines.push(inner)
      lines.push(`}`)
      lines.push("")
    }
  }

  return lines.join("\n")
}

/** Walk every array-of-object field in the schema; collect inline types by name. */
function collectInlineObjectTypes(
  schema: Schema,
): Map<string, { fields: FieldDef[]; typeName: string }> {
  const out = new Map<string, { fields: FieldDef[]; typeName: string }>()
  const visit = (field: FieldDef) => {
    if (field.type === "array") {
      for (const item of field.of) {
        if (item.type === "object" && item.typeName) {
          out.set(item.typeName, { fields: item.fields, typeName: item.typeName })
          for (const sub of item.fields) visit(sub)
        } else {
          visit(item)
        }
      }
    } else if (field.type === "object") {
      for (const sub of field.fields) visit(sub)
    }
  }
  for (const type of schema.types) for (const f of type.fields) visit(f)
  return out
}

// ---------------------------------------------------------------------------

function isOptional(field: FieldDef): boolean {
  // All fields are effectively optional in our schema — we don't have
  // required-markers yet. Be permissive.
  return true
}

function fieldType(field: FieldDef, schema: Schema): string {
  switch (field.type) {
    case "string":
    case "text":
    case "url":
      return "string"
    case "number":
      return "number"
    case "boolean":
      return "boolean"
    case "slug":
      return `{ _type?: "slug"; current: string }`
    case "image":
      return `{ _type?: "image"; url?: string; asset?: { _ref: string } }`
    case "reference": {
      const allowed = field.to
      const refUnion = allowed
        .map((t) => `DocumentByType["${t}"]["_id"]`)
        .join(" | ")
      return `{ _type: "reference"; _ref: ${refUnion || "string"} }`
    }
    case "array": {
      const itemTypes = field.of.map((f) => arrayItemType(f, schema))
      const inner = itemTypes.length === 1 ? itemTypes[0] : `(${itemTypes.join(" | ")})`
      return `${inner}[]`
    }
    case "object": {
      const inner = field.fields
        .map((f) => `${f.name}?: ${fieldType(f, schema)}`)
        .join("; ")
      const prefix = field.typeName ? `_type: "${field.typeName}"; _key: string; ` : ""
      return `{ ${prefix}${inner} }`
    }
    case "blockContent":
      return "PortableTextBlock[]"
    default:
      return "unknown"
  }
}

/**
 * A field appearing inside `array.of` needs a `_type` (and `_key`) so
 * consumers can discriminate the union.
 */
function arrayItemType(field: FieldDef, schema: Schema): string {
  if (field.type === "object") {
    const inner = field.fields.map((f) => `${f.name}?: ${fieldType(f, schema)}`).join("; ")
    const typeName = field.typeName ?? field.name
    return `{ _type: "${typeName}"; _key: string; ${inner} }`
  }
  return fieldType(field, schema)
}

function pascal(s: string): string {
  return s
    .replace(/(?:^|[_-])(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase())
}
