/**
 * Emit TypeScript type declarations for a content schema.
 *
 * Given a `Schema`, produces a `.d.ts`-style string with:
 *
 *   - One interface per document type: `export interface Post { ... }`
 *   - A discriminated union of all document types: `export type AnyDocument = Post | Author | ...`
 *   - A helper map: `export type DocumentByType = { post: Post; author: Author; ... }`
 *
 * Reference fields expand to `{ _type: "reference"; _ref: string }` by
 * default. When the referenced type is unambiguous we also emit a
 * "dereferenced" alias: `AuthorRef = { _type: "reference"; _ref: Author["_id"] }`
 * so that projections using `author->` can narrow to the target type.
 */

import type { FieldDef, Schema } from "@repo/core/schema"

export interface EmitOptions {
  /** Module path to import types from (for the query types file). Defaults to "./schema-types". */
  schemaImport?: string
  /** Add a header comment with a timestamp + warning. Defaults to true. */
  includeHeader?: boolean
}

export function emitSchemaTypes(schema: Schema, options: EmitOptions = {}): string {
  const includeHeader = options.includeHeader !== false
  const lines: string[] = []
  if (includeHeader) {
    lines.push("// Generated by @repo/typegen. Do not edit by hand.")
    lines.push("// Re-run `bun run typegen` after schema changes.")
    lines.push("")
  }

  lines.push(`/** Common base fields present on every document. */`)
  lines.push(
    `export interface SanityCloneDocument<T extends string = string> {\n` +
      `  _id: string\n` +
      `  _type: T\n` +
      `  _rev: string\n` +
      `  _createdAt: string\n` +
      `  _updatedAt: string\n` +
      `}`,
  )
  lines.push("")

  lines.push(`/** Portable Text block (rich text content). */`)
  lines.push(
    `export interface PortableTextSpan {\n` +
      `  _type: "span"\n` +
      `  _key: string\n` +
      `  text: string\n` +
      `  marks?: string[]\n` +
      `}\n` +
      `export interface PortableTextBlock {\n` +
      `  _type: "block"\n` +
      `  _key: string\n` +
      `  style: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote"\n` +
      `  children: PortableTextSpan[]\n` +
      `  markDefs?: { _key: string; _type: string; [key: string]: unknown }[]\n` +
      `}`,
  )
  lines.push("")

  for (const type of schema.types) {
    lines.push(`/** ${type.title} */`)
    lines.push(
      `export interface ${pascal(type.name)} extends SanityCloneDocument<"${type.name}"> {`,
    )
    for (const field of type.fields) {
      if (field.hidden) continue
      lines.push(`  ${field.name}${isOptional(field) ? "?" : ""}: ${fieldType(field, schema)}`)
    }
    lines.push(`}`)
    lines.push("")
  }

  const names = schema.types.map((t) => pascal(t.name))
  lines.push(`/** Any document in this schema. */`)
  lines.push(`export type AnyDocument = ${names.join(" | ")}`)
  lines.push("")
  lines.push(`/** Map from document type name to its interface. */`)
  lines.push(`export type DocumentByType = {`)
  for (const t of schema.types) {
    lines.push(`  ${t.name}: ${pascal(t.name)}`)
  }
  lines.push(`}`)
  lines.push("")

  return lines.join("\n")
}

// ---------------------------------------------------------------------------

function isOptional(field: FieldDef): boolean {
  // All fields are effectively optional in our schema — we don't have
  // required-markers yet. Be permissive.
  return true
}

function fieldType(field: FieldDef, schema: Schema): string {
  switch (field.type) {
    case "string":
    case "text":
    case "url":
      return "string"
    case "number":
      return "number"
    case "boolean":
      return "boolean"
    case "slug":
      return `{ _type?: "slug"; current: string }`
    case "image":
      return `{ _type?: "image"; url?: string; asset?: { _ref: string } }`
    case "reference": {
      const allowed = field.to
      const refUnion = allowed
        .map((t) => `DocumentByType["${t}"]["_id"]`)
        .join(" | ")
      return `{ _type: "reference"; _ref: ${refUnion || "string"} }`
    }
    case "array": {
      const itemTypes = field.of.map((f) => fieldType(f, schema))
      const inner = itemTypes.length === 1 ? itemTypes[0] : `(${itemTypes.join(" | ")})`
      return `${inner}[]`
    }
    case "object": {
      const inner = field.fields
        .map((f) => `${f.name}?: ${fieldType(f, schema)}`)
        .join("; ")
      return `{ ${inner} }`
    }
    case "blockContent":
      return "PortableTextBlock[]"
    default:
      return "unknown"
  }
}

function pascal(s: string): string {
  return s
    .replace(/(?:^|[_-])(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase())
}
