// Generated by @repo/typegen. Do not edit by hand.
// Re-run `bun run typegen` after schema changes.

/** Common base fields present on every document. */
export interface SanityCloneDocument<T extends string = string> {
  _id: string
  _type: T
  _rev: string
  _createdAt: string
  _updatedAt: string
}

/** Portable Text block (rich text content). */
export interface PortableTextSpan {
  _type: "span"
  _key: string
  text: string
  marks?: string[]
}
export interface PortableTextBlock {
  _type: "block"
  _key: string
  style: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote"
  children: PortableTextSpan[]
  markDefs?: { _key: string; _type: string; [key: string]: unknown }[]
}

/** Site Settings */
export interface SiteSettings extends SanityCloneDocument<"siteSettings"> {
  title?: string
  tagline?: string
  description?: string
}

/** Author */
export interface Author extends SanityCloneDocument<"author"> {
  name?: string
  bio?: string
}

/** Post */
export interface Post extends SanityCloneDocument<"post"> {
  title?: string
  slug?: { _type?: "slug"; current: string }
  excerpt?: string
  body?: PortableTextBlock[]
  author?: { _type: "reference"; _ref: DocumentByType["author"]["_id"] }
}

/** Page */
export interface Page extends SanityCloneDocument<"page"> {
  title?: string
  slug?: { _type?: "slug"; current: string }
  slices?: ({ _type: "heroSlice"; _key: string; heading?: string; subheading?: string; ctaLabel?: string; ctaHref?: string } | { _type: "featureGridSlice"; _key: string; heading?: string; features?: { _type: "feature"; _key: string; title?: string; description?: string }[] } | { _type: "richTextSlice"; _key: string; body?: PortableTextBlock[] } | { _type: "ctaSlice"; _key: string; heading?: string; buttonLabel?: string; buttonHref?: string })[]
}

/** Any document in this schema. */
export type AnyDocument = SiteSettings | Author | Post | Page

/** Map from document type name to its interface. */
export type DocumentByType = {
  siteSettings: SiteSettings
  author: Author
  post: Post
  page: Page
}

// --- Inline object types (for use in array.of) ---

export interface HeroSlice {
  _type: "heroSlice"
  _key: string
  heading?: string
  subheading?: string
  ctaLabel?: string
  ctaHref?: string
}

export interface FeatureGridSlice {
  _type: "featureGridSlice"
  _key: string
  heading?: string
  features?: { _type: "feature"; _key: string; title?: string; description?: string }[]
}

export interface Feature {
  _type: "feature"
  _key: string
  title?: string
  description?: string
}

export interface RichTextSlice {
  _type: "richTextSlice"
  _key: string
  body?: PortableTextBlock[]
}

export interface CtaSlice {
  _type: "ctaSlice"
  _key: string
  heading?: string
  buttonLabel?: string
  buttonHref?: string
}


// --- Query result types -------------------------------------------------

export type PostBySlugQueryResult = { _id: string; title: string; body: unknown; author: Pick<Author, "name"> | null } | null
export type PostCountQueryResult = number
export type PostListQueryResult = { _id: string; title: string; excerpt: string; slug: string }[]
export type PostSlugsQueryResult = { slug: string }[]
export type SiteSettingsQueryResult = Pick<SiteSettings, "title" | "tagline"> | null
